package cloud.autotests.tests;

import cloud.autotests.config.demowebshop.App;
import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Main page test")
    void generatedTest() {
        step("open https://goritskov.com/", () ->
                open("https://goritskov.com/"));

        step("На странице есть раздел Обо мне", () ->
            assertThat($$(By.xpath("//a[contains(@class, 'button white active blog')]")).size()).isEqualTo(1));

    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://goritskov.com/'", () ->
            open("https://goritskov.com/"));

        step("Page title should have text 'goritskov's home'", () -> {
            String expectedTitle = "goritskov's home";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://goritskov.com/'", () ->
            open("https://goritskov.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}